drop table if exists event;

create table
  event (
    id bigint primary key generated always as identity,
    venue_id int,
    host_a_id int not null,
    host_b_id int null,
    sponsoring_org_a_id int null,
    sponsoring_org_b_id int null,
    sponsoring_org_c_id int null,
    sponsoring_org_d_id int null,
    title varchar(100) not null,
    tagline varchar(72) not null,
    hashtag varchar(64) not null,
    start_date timestamp with time zone not null,
    end_date timestamp with time zone not null,
    short_description varchar(240) not null,
    long_description text null,
    target_audience varchar(120) not null,
    cost_of_attendance real default 0.0,
    location_dedicated_email varchar(140) not null,
    url_a varchar(100) null,
    url_b varchar(100) null,
    url_c varchar(100) null,
    academic boolean null default false,
    cultural boolean null default false,
    professional_development boolean null default false,
    workshop_or_training boolean null default false,
    competition boolean null default false,
    recreational boolean null default false,
    clubs_and_orgs boolean null default false,
    community_service boolean null default false,
    sports boolean null default false,
    fundraiser boolean null default false,
    awareness_campaign boolean null default false,
    political boolean null default false,
    gaming boolean null default false,
    networking boolean null default false,
    product_tech_demo boolean null default false,
    arts boolean null default false,
    entertainment boolean null default false,
    qa_session boolean default false,
    ada_compliant boolean default true,
    dress_code_theme boolean null default false,
    breakout_session boolean default false,
    serves_coffee_tea boolean default false,
    water_available boolean default true,
    catering boolean default false,
    light_snacks boolean default false,
    digital_vr_ar boolean default false,
    open_to_public boolean default true,
    giveaways boolean null default false,
    door_prizes boolean null default false,
    keynote_speaker boolean null default false,
    performances boolean null default false,
    serves_alcohol boolean default false,
    food_available boolean default false,
    live_music boolean default false,
    has_dj boolean default false,
    raffles boolean default false,
    accepts_donations boolean null default false,
    requires_permit boolean null default false,
    max_capacity int null,
    special_requirement_a varchar(100) null,
    special_requirement_b varchar(100) null,
    vibe_rating numeric(2,1)[] null,
    host_rating numeric(2,1)[] null,
    sponsor_rating numeric(2,1)[] null,
    location_rating numeric(2,1)[] null,
    value_rating numeric(2,1)[] null,
    content_rating numeric(2,1)[] null,
    programming_rating numeric(2,1)[] null,
    registrations_rsvps int null default 0,
    total_attendees int null default 0,
    production_costs numeric(10, 2) null default 0.0,
    marketing_costs numeric(10, 2) null default 0.0,
    permit_license_costs numeric(10, 2) null default 0.0,
    insurance_cost numeric(10, 2) null default 0.0,
    technology_costs numeric(10, 2) null default 0.0,
    catering_food_costs numeric(10, 2) null default 0.0,
    revenue_from_ads numeric(10, 2) null default 0.0,
    logistics_costs numeric(10, 2) null default 0.0,
    venue_costs numeric(10, 2) null default 0.0,
    personnel_staff_costs numeric(10, 2) default 0.0,
    talent_accomodation_cost numeric(10, 2) default 0.0,
    ticket_revenue numeric(10, 2) default 0.0,
    sponsor_revenue numeric(10, 2) default 0.0,
    vendor_revenue numeric(10, 2) default 0.0,
    ad_revenue numeric(10, 2) default 0.0,
    merch_revenue numeric(10, 2) default 0.0,
    concessions_revenue numeric(10, 2) default 0.0,
    donations_revenue numeric(10, 2) default 0.0,
    workshop_cert_revenue numeric(10, 2) default 0.0,
    misc_raffle_revenue numeric(10, 2) default 0.0,
    additional_notes varchar(240) null,
    unique (title),
    foreign key (venue_id) references spatial_domain (id) on delete cascade,
    foreign key (host_a_id) references person (id) on delete cascade,
    foreign key (host_b_id) references person (id) on delete cascade,
    foreign key (sponsoring_org_a_id) references organization (id) on delete cascade,
    foreign key (sponsoring_org_b_id) references organization (id) on delete cascade,
    foreign key (sponsoring_org_c_id) references organization (id) on delete cascade,
    foreign key (sponsoring_org_d_id) references organization (id) on delete cascade
  );
