drop table if exists person;
create table person (
    id bigint primary key generated always as identity,
    alias varchar(140) not null,
    firstName varchar(140) not null,
    lastName varchar(140) not null,
    birth_month int4range null,
    birth_day int4range null,
    birth_year int4range null,
    emailAddress varchar(240) not null,
    minor boolean null default false,
    student boolean null default true,
    publicSafetyOfficial boolean null default false,
    campusSchoolAdmin boolean null default false,
    municipalGovOfficial boolean null default false,
    accountOrignDate timestamp with time zone null default current_timestamp,
    canReportEmergencies boolean null default true,
    canCreateInAppEvent boolean null default true,
    canCreateSafetyBulletin boolean default false,
    canViewSafetyBulletin boolean default true,
    canViewEmergencyAlerts boolean default true,
    canMakeRequestOnExtrinsicAcct boolean default false,
    allowsRequestsOnAccount boolean default false,
    notificationAllEmergencies boolean null default true,
    notificationRelativeEmergencies boolean null default true,
    notificationNonEmergencies boolean null default true,
    notificationRequestOnAccountMade boolean null default true,
    numOfProfileUpdates int null default 0,
    lastKnownLocation point null,
    unique (emailAddress, alias)
  );
